### ISSUE TITLE
extracting confidence intervals from output

### ISSUE THREAD

**Issue by sam81** [danilinares/quickpsy#14]
Hi, first of all, thanks for creating this very useful package. I'm using version `0.1.3`, and I can't figure our how to extract the bootstrap confidence intervals from the output of a call to `quickpsy`. I'm calling the function as follows:

    res = quickpsy(theseDats, x=log(adaptive_difference), k=response, fun=logistic_fun, log=F, lapse=T, bootstrap='parametric', guess=0.5, optimization = 'optim', parini=list(c(min(log(theseDats$adaptive_difference)), max(log(theseDats$adaptive_difference))), c(0.01, 10), c(0, 0.25)), B=1000)

the documentation of the `quickpsy` function suggests that the confidence intervals should be a component of the output list named `paraci`, but I'm unable to find such component, my output has the following structure (sorry for the long output):

    str(res, max.level=1)
    List of 31
     $ x                   : chr "log(adaptive_difference)"
     $ k                   : chr "response"
     $ n                   : chr "n"
     $ guess               : num 0.5
     $ lapses              : logi TRUE
     $ averages            :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	151 obs. of  4 variables:
     $ groups              : chr(0) 
     $ funname             : chr "logistic_fun"
     $ log                 : logi FALSE
     $ psyfunguesslapses   :function (x, p)  
     $ limits              :'data.frame':	1 obs. of  2 variables:
     $ pariniset           : logi TRUE
     $ parini              :List of 3
     $ optimization        : chr "optim"
     $ par                 :'data.frame':	3 obs. of  4 variables:
     $ pariniset           : logi TRUE
     $ ypred               :'data.frame':	151 obs. of  2 variables:
     $ curves              :'data.frame':	300 obs. of  2 variables:
     $ sse                 :'data.frame':	1 obs. of  1 variable:
     $ thresholds          :'data.frame':	1 obs. of  4 variables:
     $ logliks             :'data.frame':	1 obs. of  1 variable:
     $ loglikssaturated    :'data.frame':	1 obs. of  1 variable:
     $ deviance            :'data.frame':	1 obs. of  2 variables:
     $ avbootstrap         :Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	151000 obs. of  5 variables:
      ..- attr(*, "vars")=List of 1
      ..- attr(*, "drop")= logi TRUE
      ..- attr(*, "indices")=List of 1000
      .. .. [list output truncated]
      ..- attr(*, "group_sizes")= int [1:1000] 151 151 151 151 151 151 151 151 151 151 ...
      ..- attr(*, "biggest_group_size")= int 151
      ..- attr(*, "labels")='data.frame':	1000 obs. of  1 variable:
      .. ..- attr(*, "vars")=List of 1
      .. ..- attr(*, "drop")= logi TRUE
     $ parbootstrap        :Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	3000 obs. of  3 variables:
      ..- attr(*, "vars")=List of 1
      ..- attr(*, "drop")= logi TRUE
      ..- attr(*, "indices")=List of 1000
      .. .. [list output truncated]
      ..- attr(*, "group_sizes")= int [1:1000] 3 3 3 3 3 3 3 3 3 3 ...
      ..- attr(*, "biggest_group_size")= int 3
      ..- attr(*, "labels")='data.frame':	1000 obs. of  1 variable:
      .. ..- attr(*, "vars")=List of 1
      .. ..- attr(*, "drop")= logi TRUE
     $ logliksboot         :Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	1000 obs. of  2 variables:
      ..- attr(*, "vars")=List of 1
      ..- attr(*, "drop")= logi TRUE
      ..- attr(*, "indices")=List of 1000
      .. .. [list output truncated]
      ..- attr(*, "group_sizes")= int [1:1000] 1 1 1 1 1 1 1 1 1 1 ...
      ..- attr(*, "biggest_group_size")= int 1
      ..- attr(*, "labels")='data.frame':	1000 obs. of  1 variable:
      .. ..- attr(*, "vars")=List of 1
      .. ..- attr(*, "drop")= logi TRUE
     $ logliksbootsaturated:Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	1000 obs. of  2 variables:
      ..- attr(*, "vars")=List of 1
      ..- attr(*, "drop")= logi TRUE
      ..- attr(*, "indices")=List of 1000
      .. .. [list output truncated]
      ..- attr(*, "group_sizes")= int [1:1000] 1 1 1 1 1 1 1 1 1 1 ...
      ..- attr(*, "biggest_group_size")= int 1
      ..- attr(*, "labels")='data.frame':	1000 obs. of  1 variable:
      .. ..- attr(*, "vars")=List of 1
      .. ..- attr(*, "drop")= logi TRUE
     $ devianceboot        :Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	1000 obs. of  2 variables:
      ..- attr(*, "vars")=List of 1
      ..- attr(*, "drop")= logi TRUE
      ..- attr(*, "indices")=List of 1000
      .. .. [list output truncated]
      ..- attr(*, "group_sizes")= int [1:1000] 1 1 1 1 1 1 1 1 1 1 ...
      ..- attr(*, "biggest_group_size")= int 1
      ..- attr(*, "labels")='data.frame':	1000 obs. of  1 variable:
      .. ..- attr(*, "vars")=List of 1
      .. ..- attr(*, "drop")= logi TRUE
     $ aic                 :'data.frame':	1 obs. of  1 variable:
     $ curvesbootstrap     :Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	300000 obs. of  3 variables:
      ..- attr(*, "vars")=List of 1
      ..- attr(*, "drop")= logi TRUE
      ..- attr(*, "indices")=List of 1000
      .. .. [list output truncated]
      ..- attr(*, "group_sizes")= int [1:1000] 300 300 300 300 300 300 300 300 300 300 ...
      ..- attr(*, "biggest_group_size")= int 300
      ..- attr(*, "labels")='data.frame':	1000 obs. of  1 variable:
      .. ..- attr(*, "vars")=List of 1
      .. ..- attr(*, "drop")= logi TRUE
     $ thresholdsbootstrap :Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	1000 obs. of  3 variables:
      ..- attr(*, "vars")=List of 1
      ..- attr(*, "drop")= logi TRUE
      ..- attr(*, "indices")=List of 1000
      .. .. [list output truncated]
      ..- attr(*, "group_sizes")= int [1:1000] 1 1 1 1 1 1 1 1 1 1 ...
      ..- attr(*, "biggest_group_size")= int 1
      ..- attr(*, "labels")='data.frame':	1000 obs. of  1 variable:
      .. ..- attr(*, "vars")=List of 1
      .. ..- attr(*, "drop")= logi TRUE
     - attr(*, "class")= chr "quickpsy"

**Comment by danilinares** [comment]
We deprecated paraci. Now, the confidence intervals are integrate in res$para. We forgot to update the documentation. Thanks for pointing it out.

**Comment by sam81** [comment]
thanks, there is one thing I'm still not clear about, when I use the `print` method on the output I get the following:

    > print(res)
      parn       par    parinf      parsup
    1   p1 -1.199665 -1.545235 -0.96348790
    2   p2  2.864154  1.560622 10.00000000
    3   p3  0.000000  0.000000  0.09587308
    NULL
           thre prob  threinf    thresup
    1 -1.199665 0.75 -1.51627 -0.9634879

the second line and the last line of the output both refer to the threshold parameter as far as I understand. The lower bound of the confidence interval however is slightly different in the second and last line. What is the reason for this?

**Comment by danilinares** [comment]
I think that once you have lapses, the position parameter of the logistic does not coincide with the threshold. 

Psi =  gamma + (1 - gamma - lambda) (1 + exp(-beta * (x - alpha)))^(-1)
3/4 =  1/2 + (1 - 1/2 - lambda) (1 + exp(-beta * (x_threshold - alpha)))^(-1)
... 
...
x_threshold = alpha - 1/ beta * log (1-4 lambda) (if i didn't make any mistake in the calculation).

**Comment by sam81** [comment]
thanks, that makes sense.
