### ISSUE TITLE
Can't pass a variable to groups in quickpsy

### ISSUE THREAD

**Issue by alexholcombe** [danilinares/quickpsy#3]
Having trouble getting a variable interpreted when I pass a variable for the grouping. E.g. this variable:

`factors = c("condName","subject","leftOrRight")`

The below works.
`
fit <- quickpsy(datDani, speed, correct, grouping=c("condName","subject","leftOrRight"))`
This doesn't:
`
  fit <- quickpsy(datDani, speed, correct, grouping=factors, bootstrap='none') #DOESNT WORK. Only uses first element
`

**Comment by danilinares** [comment]
How about trying quickpsy_ ? :

fit <- quickpsy_(datDani, 'speed', 'correct', grouping=factors, bootstrap='none')

**Comment by alexholcombe** [comment]
Thanks yes that works! So, the line in quickpsy that causes the problem is
`grouping <- as.character(substitute(grouping))[-1]`
It seems that this could be fixed by adding a line of code that tests whether what was passed to quickpsy was an expression like `c("orientation","frequency")` or instead a variable. I'm sure the answer is hiding somewhere on this page http://adv-r.had.co.nz/Expressions.html
but I don't know the first thing about all this meta-variable stuff in R. Maybe you do, since you used a bunch of it for the quickpsy wrapper...

**Comment by danilinares** [comment]
quickpsy_ will be deprecated in favour of the new NSE model: https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html
