### ISSUE TITLE
Slopes of individual curves 

### ISSUE THREAD

**Issue by aftmnelbier11** [danilinares/quickpsy#34]
In the quickpsy output list, do one of the entries include the individual slopes of each subject (as a measure of individual response distinction)? I looked but thought maybe they might be labelled as something else.

**Comment by danilinares** [comment]
In the data frame "par" from the output list, p2 corresponds to the standard deviation of the cumulative normal distribution, which is the default psychometric function fitted to the data. You can provide other functions in the fun argument like the logistic: (1 + exp(-p[2] * (x - p[1])))^(-1)

**Comment by aftmnelbier11** [comment]
Ah okay! To make sure I understood correctly: if I am using a logistic function for the model, the "par" in the output is the alpha and beta, which would correspond to the threshold and slope, respectively?

**Comment by danilinares** [comment]
The p1 and p2 are the parameters of this expression of the logistic: (1 + exp(-p[2] * (x - p[1])))^(-1)

**Comment by aftmnelbier11** [comment]
Thank you for your clarifications!!
